apiVersion: apps/v1
kind: Deployment # 指定资源类别
metadata: #资源的一些元数据
  name: grpc-spring-cloud-provider #deloyment的名称
  labels:
    app: grpc-spring-cloud-provider  #标签
spec:
  replicas: 3 #创建pod的个数
  selector:
    matchLabels:
      app: grpc-spring-cloud-provider #满足标签为这个的时候相关的pod才能被调度到
  template:
    metadata:
      labels:
        app: grpc-spring-cloud-provider
    spec:
      containers:
        - name: grpc-spring-cloud-provider
          image: grpc-spring-cloud-provider:1
          imagePullPolicy: IfNotPresent #当本地有镜像的时候优先选用本地，没有才选择网络拉取
          ports:
            - containerPort: 8782 #开放8080
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-spring-cloud-provider
spec:
  selector:
    app: grpc-spring-cloud-provider
  ports:
    - protocol: TCP
      port: 8782
      targetPort: 8782
      nodePort: 32111
  type: NodePort
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: grpc-spring-cloud-provider
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
